version: "3"

services:
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: pfa-mysql
    restart: always
    tty: true
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - pfa-docker

  node:
    build:
      context: node
    container_name: pfa-node
    entrypoint: dockerize -wait tcp://pfa-mysql:3306 -timeout 30s node index.js
    networks:
      - pfa-docker
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: pfa-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pfa-docker
    ports:
      - 8000:80
    restart: always

networks:
  pfa-docker:
    driver: bridge