version: "3"

services:
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: pfa-mysql
    restart: always
    tty: true
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - pfa-docker-internal

  node:
    build:
      context: node
    container_name: pfa-node
    command: dockerize -wait tcp://pfa-mysql:3306 -timeout 30s node ./dist/index.js
    networks:
      - pfa-docker-external
      - pfa-docker-internal
    volumes:
      - /usr/src/app
    tty: true
    depends_on:
      - mysql

  nginx:
    build: ./nginx
    container_name: pfa-nginx
    entrypoint: dockerize -wait tcp://pfa-node:3000 -timeout 60s /docker-entrypoint.sh nginx -g 'daemon off;'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pfa-docker-external
    ports:
      - 8000:80
    restart: always
    depends_on:
      - node

networks:
  pfa-docker-internal:
    driver: bridge
  pfa-docker-external:
    driver: bridge